apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartops-policy-engine
  namespace: smartops-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smartops-policy-engine
  template:
    metadata:
      labels:
        app: smartops-policy-engine
    spec:
      containers:
        - name: policy-engine
          image: smartops-policy-engine:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8002
          env:
            - name: POLICY_ENGINE_PORT
              value: "8002"
            - name: PYTHONPATH
              value: "/app"
            - name: POLICY_STORE_PATH
              value: "/policy_engine/store/policies.json"
            - name: SMARTOPS_ADMIN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: smartops-admin-secret
                  key: SMARTOPS_ADMIN_API_KEY
          volumeMounts:
            - name: policy-store
              mountPath: /policy_engine/store
      volumes:
        - name: policy-store
          persistentVolumeClaim:
            claimName: policy-store-pvc
